version: '3.4'

services:
  daycare.web:
    image: ${DOCKER_REGISTRY-}daycare.web
    build:
      context: .
      dockerfile: DayCare.Web/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Password123
    ports:
    - 1433:1433
