on:
  push:
    branches:
    - master
env:
  CONTAINER_REGISTRY_LOGIN_SERVER: daycare20231105104604.azurecr.io
  PROJECT_NAME_FOR_DOCKER: daycare.web
  CONTAINER_APP_NAME: daycare20231105104246
  CONTAINER_APP_RESOURCE_GROUP_NAME: daycare20231105104246ResourceGroup
  CONTAINER_APP_CONTAINER_NAME: daycare
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.daycare20231105104604_USERNAME_A490 }}
        password: ${{ secrets.daycare20231105104604_PASSWORD_A490 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: DayCare.Web/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.daycare20231105104246_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.daycare20231105104604_USERNAME_A490 }} --password ${{ secrets.daycare20231105104604_PASSWORD_A490 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: Azure logout
      run: az logout
