on:
  push:
    branches:
    - master
env:
  CONTAINER_REGISTRY_LOGIN_SERVER: daycarecontainerregistry202311101331.azurecr.io
  PROJECT_NAME_FOR_DOCKER: daycare.web
jobs:
  buildImage:
    name: "Build and push Docker image to Azure container registry"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.daycare20231105104604_USERNAME_A490 }}
        password: ${{ secrets.daycare20231105104604_PASSWORD_A490 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} , ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:latest 
        file: DayCare.Web/Dockerfile

  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy stacks
        env:
          CONTAINER_APP_IMAGE: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          cd DayCare.Azure
          npm install -g cdktf-cli
          npx cdktf deploy --auto-approve --no-color infrastructureStack
          npx cdktf deploy --auto-approve --no-color migrationsStack
          npx cdktf deploy --auto-approve --no-color applicationStack
